#### Explore silver.orders

In [4]:
from warehouse import Warehouse

with Warehouse() as wh:
    df_orders = wh.read_table(name="orders", schema="silver")
df_orders.info()
df_orders.head()

<class 'pandas.DataFrame'>
RangeIndex: 2371 entries, 0 to 2370
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          2371 non-null   str
 1   order_name        2371 non-null   str
 2   processed_at      2371 non-null   datetime64[us]
 3   created_at        2371 non-null   datetime64[us]
 4   financial_status  2371 non-null   str
 5   total_amount      2371 non-null   float64
 6   currency          2371 non-null   str
 7   source            2341 non-null   str
 8   customer_id       2328 non-null   str
dtypes: datetime64[us](2), float64(1), str(6)
memory usage: 166.8 KB

,order_id,order_name,processed_at,created_at,financial_status,total_amount,currency,source,customer_id
0,6863460728903,#1944,2025-08-06 21:59:11,2026-08-07 08:43:48,PAID,389.85,USD,direct,8899950706759
1,6863063973959,#1593,2025-08-06 22:26:15,2026-08-07 07:30:32,PAID,649.80,USD,google,8900800446535
2,6867039912007,#2637,2025-08-07 09:44:12,2026-08-07 15:02:08,PAID,2769.65,USD,organic,8901292359751
3,6863064105031,#1594,2025-08-07 10:08:20,2026-08-07 07:30:45,PAID,739.90,USD,direct,8900800544839
4,6862370635847,#1219,2025-08-07 13:08:37,2026-08-07 05:20:57,PAID,1559.50,USD,google,8894398300231

#### Explore silver.order_items

In [5]:
from warehouse import Warehouse

with Warehouse() as wh:
    df_order_items = wh.read_table(name="order_items", schema="silver")
df_order_items.info()
df_order_items.head()

<class 'pandas.DataFrame'>
RangeIndex: 7060 entries, 0 to 7059
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      7060 non-null   str
 1   product_id    7059 non-null   str
 2   title         7060 non-null   str
 3   quantity      7060 non-null   int64
 4   product_type  7059 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.9 KB

,order_id,product_id,title,quantity,product_type
0,6863460728903,7624730968135,VANS | OLD SKOOL (BUTTERFLY) TRUE WHITE | BLACK,3,SHOES
1,6863063973959,7624727101511,VANS | AUTHENTIC (BUTTERFLY) TRUE | WHITE / BLACK,1,SHOES
2,6863063973959,7624727822407,VANS | SK8-HI DECON (CUTOUT)| LEAVES/WHITE,3,SHOES
3,6867039912007,7624728248391,ASICS TIGER | GEL-LYTE V '30 YEARS OF GEL' PACK,2,SHOES
4,6867039912007,7624729919559,VANS | ERA 59 (DESERT COWBOY),3,SHOES

#### Explore silver.products

In [6]:
from warehouse import Warehouse

with Warehouse() as wh:
    df_products = wh.read_table(name="products", schema="silver")
df_products.info()
df_products.head()

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    47 non-null     str
 1   title         47 non-null     str
 2   product_type  46 non-null     str
 3   vendor        47 non-null     str
 4   tags          47 non-null     str
 5   status        47 non-null     str
 6   created_at    47 non-null     datetime64[us]
dtypes: datetime64[us](1), str(6)
memory usage: 2.7 KB

,product_id,title,product_type,vendor,tags,status,created_at
0,7623609647175,The Inventory Not Tracked Snowboard,Snowboard,Ofek-Dev-Store,"Accessory,Sport,Winter",ACTIVE,2026-08-05 18:31:42
1,7623609679943,Gift Card,Giftcard,Snowboard Vendor,,ACTIVE,2026-08-05 18:31:42
2,7623609778247,The Compare at Price Snowboard,Snowboard,Ofek-Dev-Store,"Accessory,Sport,Winter",ACTIVE,2026-08-05 18:31:42
3,7623609811015,The Archived Snowboard,Snowboard,Snowboard Vendor,"Archived,Premium,Snow,Snowboard,Sport,Winter",ARCHIVED,2026-08-05 18:31:42
4,7623609843783,The Draft Snowboard,Snowboard,Snowboard Vendor,,DRAFT,2026-08-05 18:31:42